### ISSUE TITLE
Add "Fishing" to CraftSkill

### ISSUE THREAD

**Issue by jaytonic** [MaxNau/ArtifactsMMO.NET#7]
Hi @MaxNau 

Thanks for the great library! I'm currently removing my whole implementation to use yours since it was quite similar.

I'm just wondering if you(or I could make a PR) could add "Fishing" as a "CraftSkill" ?

The reasons is that it's the only skill that is not in it, and even if I understand that you cannot "craft" fish, it prevents a lot of general behavior because there will be no enum that contains all the skills.

like

`int character.GetLevel(CraftSkill skill);`

or some logic to improve any skill

`myBot.Improve(CraftSkill skill);`

What do you think? 

Note, I saw that you also have `TaskSkill`, but it's a bit a pain to have to implement twice methods like "GetLevel", once for the crafting skill once for the general skill?

**Comment by jaytonic** [comment]
Also, I guess the `MapContent.Type` should be of type `MapContentType` that you also already have

**Comment by MaxNau** [comment]
Hi @jaytonic ,

Thank you for your positive feedback about the library! I'm glad to hear that it's fitting well with your implementation.

I appreciate your suggestion to add an enum for all character skills. I’ll definitely think about it, and if I see some support from others in the community, I’ll consider moving forward with that change.

> Also, I guess the `MapContent.Type` should be of type `MapContentType` that you also already have(same for Item.Type)

Thank you for noticing that. I will fix it in the hotfix for 2.4.1 version.

Your input is valuable, and I’m always open to ideas that can enhance the library. If you have any more suggestions or need help, feel free to reach out!

**Comment by MaxNau** [comment]
I will add new enum - CharacterSkill that will have all the skills available in the game, since CraftSkill is used as a filter in queries and fishing is not one of the allowed values.

**Comment by MaxNau** [comment]
Added CharacterSkill enum in PR #13
